### ISSUE TITLE
I traped into the cycle, when I run the Demo.

### ISSUE THREAD

**Issue by ningquan-gu** [real-stanford/cloth-funnels#1]
I tried to run the Demo Cloth Funnels. But the program is trapped into the cycle.
The 587 line of the cloth_funnels/tasks/generate_task.py
```
 if self.curr_task_idx >= len(self.keys):
    print('[TaskLoader] Out of tasks')
    # sleep(20)
    # exit(0)
    while True:
        sleep(5)
```
The terminal has no new output.

blender 2.79

**Comment by xiaolijz** [comment]
> I tried to run the Demo Cloth Funnels. But the program is trapped into the cycle. The 587 line of the cloth_funnels/tasks/generate_task.py
> 
> ```
>  if self.curr_task_idx >= len(self.keys):
>     print('[TaskLoader] Out of tasks')
>     # sleep(20)
>     # exit(0)
>     while True:
>         sleep(5)
> ```
> 
> The terminal has no new output.
> 
> blender 2.79

Hello, have you successfully run this project?
